transcendence/transcendence/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('website.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.IMGS_URL, document_root=settings.IMGS_ROOT)

transcendence/website/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import handler404
from .views import register
from django.conf import settings
from django.conf.urls.static import static
from .views import change_language

urlpatterns = [
		path('', views.main, name='main'),
		path('main/', views.main, name='main'),
		path('players/', views.players, name='players'),
		path('players/details/<int:id>', views.details, name='details'),
		path('login/', views.login_view, name='login'),
		path('register/', views.register, name='register'),
		path('logout/', views.logout_view, name='logout'),
		path('profile/', views.profile, name='profile'),
		path('pong_welcome/', views.pong_welcome, name='pong_welcome'),
		path('brique/', views.brique, name='brique'),
		path('test/', views.test, name='test'),
        path('increment_game/<int:player_id>/', views.increment_game, name='increment_game'),			#bouton +1 game (pong)
		path('increment_victory/<int:player_id>/', views.increment_victory, name='increment_victory'),	#bouton +1 victoire
		path('increment_defeat/<int:player_id>/', views.increment_defeat, name='increment_defeat'),		#bouton +1 défaite
		path('decrement_victory/<int:player_id>/', views.decrement_victory, name='decrement_victory'),	#bouton -1 victoire
		path('decrement_defeat/<int:player_id>/', views.decrement_defeat, name='decrement_defeat'),		#bouton -1 défaite
		path('resetWL/<int:player_id>/', views.resetWL, name='resetWL'),						#bouton reset Win et Lose
        path('check_login/', views.check_login, name='check_login'),
		path('add_friend/<int:id>/', views.add_friend, name='add_friend'),
		path('remove_friend/<int:id>/', views.remove_friend, name='remove_friend'),
		path('accept_friend_request/<int:id>/', views.accept_friend_request, name='accept_friend_request'),
		path('decline_friend_request/<int:id>/', views.decline_friend_request, name='decline_friend_request'),
		path('pong/sendscore/', views.sendscore, name='sendscore'),
		path('pong/two_players/', views.two_players, name='two_players'),
		path('pong/vs_ai/', views.vs_ai, name='vs_ai'),
		path('pong/end_game/', views.end_game, name='end_game'),
		path('change_language/', change_language, name='change_language'),
		path('brique/sendscore/', views.sendscore_brique, name='sendscore_brique'),
		path('brique/end_game/', views.end_game, name='end_game'),
		path('pong/tournament/', views.tournament, name='tournament'),
		path('create_tournament/', views.create_tournament, name='create_tournament'),
		path('join_tournament/', views.join_tournament, name='join_tournament'),
		path('leave_tournament/', views.leave_tournament, name='leave_tournament'),
		path('play_match/<int:match_id>/', views.play_match, name='play_match'),
		path('verify_password/', views.verify_password, name='verify_password'),
		path('pong/sendmatchscore/', views.sendmatchscore, name='sendmatchscore'),
		path('pong/force_create/', views.force_create, name='force_create'),
]

handler404 = 'website.views.handler404'

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.IMGS_URL, document_root=settings.IMGS_ROOT)

transcendence/website/models.py
import datetime
import random
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db.models import Manager, Max

# Create your models here.

class User(AbstractUser):
    date_joined = models.DateTimeField(auto_now_add=True)
    language = models.CharField(max_length=2, default='en')
    total_pong_games = models.IntegerField(default=0)
    pong_victories = models.IntegerField(default=0)
    pong_defeats = models.IntegerField(default=0)
    pong_points_for = models.IntegerField(default=0)
    pong_points_against = models.IntegerField(default=0)
    pong_wl_ratio = models.FloatField(default=0)
    pong_points_ratio = models.FloatField(default=0)
    pong_average_for = models.FloatField(default=0)
    pong_average_against = models.FloatField(default=0)
    pong_victories_percentage = models.FloatField(default=0)
    pong_defeats_percentage = models.FloatField(default=0)
    brick_games = models.IntegerField(default=0)
    brick_points = models.IntegerField(default=0)
    brick_average = models.FloatField(default=0)
    avatar = models.ImageField(upload_to='avatars/', default='avatars/default.png', blank=True, null=True)
    last_activity = models.DateTimeField(auto_now=True)
    is_in_game = models.BooleanField(default=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._original_pong_defeats = self.pong_defeats
        self._original_pong_victories = self.pong_victories

    def __str__(self):
        return f"{self.id} {self.email}"

    def calculate_percentages(self):
        total_games = self.pong_victories + self.pong_defeats
        if total_games > 0:
            self.pong_victories_percentage = (self.pong_victories / total_games) * 100
            self.pong_defeats_percentage = (self.pong_defeats / total_games) * 100
        else:
            self.pong_victories_percentage = 0
            self.pong_defeats_percentage = 0

    def save(self, *args, **kwargs):
        if self.username == 'user':
            super().save(*args, **kwargs)
            self.username = 'user' + str(self.id)
        if self.pong_defeats != self._original_pong_defeats or self.pong_victories != self._original_pong_victories:
            self.calculate_percentages()
        super().save(*args, **kwargs)
        self._original_pong_defeats = self.pong_defeats
        self._original_pong_victories = self.pong_victories

    def are_friends(self, user):
        return Friendship.objects.filter(user1=self, user2=user).exists() or Friendship.objects.filter(user1=user, user2=self).exists()

    def is_online(self):
        return self.last_activity > timezone.now() - datetime.timedelta(minutes=5)

class Friendship(models.Model):
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user1')
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user2')
    is_pending = models.BooleanField(default=False)
    is_confirmed = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['user1', 'user2']

    def __str__(self):
        return f"{self.user1} is friend with {self.user2}"
    
class GameRecord(models.Model):
    PONG = 'PONG'
    BRICK = 'BRICK'
    PONGT = 'PONGTOURNAMENT'
    GAME_CHOICES = [
        (PONG, 'Pong'),
        (BRICK, 'Brick'),
        (PONGT, 'Pong Tournament')
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='game_records')
    game_type = models.CharField(max_length=14, choices=GAME_CHOICES)
    score_left = models.IntegerField(null=True, blank=True)
    score_right = models.IntegerField(null=True, blank=True)
    score = models.IntegerField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} played {self.get_game_type_display()}"
    
    def save(self, *args, **kwargs):
        if self.game_type == 'PONG':
            if self.score_left is None or self.score_right is None:
                raise ValidationError('Pong game must have both scores')
            self.score = None
        elif self.game_type == 'BRICK':
            if self.score is None:
                raise ValidationError('Brick game must have a score')
            self.score_left = None
            self.score_right = None

        super().save(*args, **kwargs)

class TournamentManager(Manager):
    def get_tournament_with_most_players(self):
        tournaments = self.filter(nb_players__lt=8)
        tournament = tournaments.order_by('-nb_players').first()
        return tournament
    
    def get_user_tournament(self, user):
        return self.filter(players=user).first()
    
    def get_user_match(self, user):
        tournaments = self.filter(is_active=True, players=user)
        for tournament in tournaments:
            # Récupérer les matchs de l'utilisateur dans le tournoi
            matches = tournament.matches.filter(
                models.Q(participant1__user=user) | models.Q(participant2__user=user),
                score_participant1__isnull=True,
                score_participant2__isnull=True
            )
            if matches.exists():
                return matches.first()
        return None

class Tournament(models.Model):
    create_date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=False)
    is_started = models.BooleanField(default=False)
    nb_players = models.IntegerField(default=0)
    players = models.ManyToManyField(User, through='Participant', related_name='tournaments')
    quarters = models.JSONField(default=list)
    semis = models.JSONField(default=list)
    final = models.IntegerField(null=True, blank=True)
    objects = TournamentManager()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def create_initial_matches(self):
        if not self.pk:
            raise ValueError("Tournament must be saved before creating matches")

        quarter_final_matches = [Match(tournament=self, round=1, pos='top' if i < 2 else 'bottom') for i in range(4)]
        semi_final_matches = [Match(tournament=self, round=2) for _ in range(2)]
        final_match = [Match(tournament=self, round=3)]

        Match.objects.bulk_create(quarter_final_matches + semi_final_matches + final_match)

    def add_participant(self, user):
        used_seeds = Participant.objects.filter(tournament=self).values_list('seed', flat=True)
        all_seeds = list(range(1, 9))
        unused_seeds = [seed for seed in all_seeds if seed not in used_seeds]
        seed = random.choice(unused_seeds)
        Participant.objects.create(user=user, tournament=self, seed=seed)
        self.nb_players += 1
        self.save()
        if self.nb_players == 8:
            self.generate_matches()
    
    def remove_participant(self, user):
        participant = Participant.objects.get(user=user, tournament=self)
        participant.delete()
        self.nb_players -= 1
        self.save()

    def generate_matches(self):
        if self.nb_players != 8:
            raise ValidationError('Tournament must have 8 players')

        self.matches.all().delete()
        self.create_initial_matches()

        # Récupérer les matchs vides et ajouter les participants
        quarters_matches = self.get_matches_by_round(1)
        participants = list(self.participants.all())
        random.shuffle(participants)

        for match, participant_pair in zip(quarters_matches, zip(participants[::2], participants[1::2])):
            match.participant1, match.participant2 = participant_pair
            match.save()
        self.is_started = True

    def get_matches_by_round(self, round_number):
        return self.matches.filter(round=round_number)
    
    def delete_tournament(self):
        self.matches.all().delete()
        self.delete()


class Participant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, related_name='participants')
    seed = models.IntegerField()

class Match(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, related_name='matches')
    participant1 = models.ForeignKey(Participant, on_delete=models.CASCADE, related_name='matches_as_player1', null=True)
    participant2 = models.ForeignKey(Participant, on_delete=models.CASCADE, related_name='matches_as_player2', null=True)
    score_participant1 = models.IntegerField(null=True, blank=True)
    score_participant2 = models.IntegerField(null=True, blank=True)
    winner = models.ForeignKey(Participant, on_delete=models.SET_NULL, null=True, blank=True, related_name='won_matches')
    round = models.IntegerField(default=1)
    POS_CHOICES = [
        ('top', 'Top'),
        ('bottom', 'Bottom'),
    ]
    pos = models.CharField(max_length=6, choices=POS_CHOICES, null=True, blank=True)

    def save(self, *args, **kwargs):
        updating_winner = self.pk is not None and (self.score_participant1 is not None and self.score_participant2 is not None)
        super().save(*args, **kwargs)

        if updating_winner:
            self.winner = self.participant1 if self.score_participant1 > self.score_participant2 else self.participant2
            print("winner :")
            print(self.winner.user.username)
            super().save(*args, **kwargs)

            if self.round == 1:  # Match de quart de finale
                next_round = self.round + 1
                next_matches = Match.objects.filter(tournament=self.tournament, round=next_round)
                
                for next_match in next_matches:
                    if next_match.pos is None:
                        next_match.pos = self.pos

transcendence/website/forms.py
from django import forms
from .models import User
from django.utils.safestring import mark_safe
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.forms.widgets import ClearableFileInput

class UserForm(UserCreationForm):
    avatar = forms.ImageField(label='Avatar', required=False, help_text=mark_safe('<br>Upload your avatar here'))
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('email', 'avatar')

from django import forms
from django.contrib.auth.forms import PasswordChangeForm

class ChangePasswordFormEn(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(ChangePasswordFormEn, self).__init__(*args, **kwargs)

        self.fields['old_password'].label = 'Old password'
        self.fields['old_password'].help_text = 'Enter your old password'

        self.fields['new_password1'].label = 'New password'
        self.fields['new_password1'].help_text = 'Enter your new password'

        self.fields['new_password2'].label = 'Confirmation'
        self.fields['new_password2'].help_text = 'Confirm your password'

class ChangePasswordFormFr(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(ChangePasswordFormFr, self).__init__(*args, **kwargs)

        self.fields['old_password'].label = 'Ancien mot de passe'
        self.fields['old_password'].help_text = 'Entrer votre ancien mot de passe'

        self.fields['new_password1'].label = 'Nouveau mot de passe'
        self.fields['new_password1'].help_text = 'Entrer votre nouveau mot de passe'

        self.fields['new_password2'].label = 'Confirmation'
        self.fields['new_password2'].help_text = 'Confirmez votre mot de passe'

class ChangePasswordFormSp(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(ChangePasswordFormSp, self).__init__(*args, **kwargs)

        self.fields['old_password'].label = 'Antigua contraseña'
        self.fields['old_password'].help_text = 'Ingrese su antigua contraseña'

        self.fields['new_password1'].label = 'Nueva contraseña'
        self.fields['new_password1'].help_text = 'Ingrese su nueva contraseña'

        self.fields['new_password2'].label = 'Confirmación'
        self.fields['new_password2'].help_text = 'Confirme su contraseña'

class CustomClearableFileInputEn(ClearableFileInput):
    template_name = 'custom_clearable_file_inputEn.html'

class CustomClearableFileInputFr(ClearableFileInput):
    template_name = 'custom_clearable_file_inputFr.html'

class CustomClearableFileInputSp(ClearableFileInput):
    template_name = 'custom_clearable_file_inputSp.html'

class ChangeAvatarFormEn(forms.ModelForm):
    avatar = forms.ImageField(label='Your Avatar', required=True, widget=CustomClearableFileInputEn(attrs={'class': 'form-control'}), )
    class Meta:
        model = User
        fields = ['avatar']

class ChangeAvatarFormFr(forms.ModelForm):
    avatar = forms.ImageField(label='Your Avatar', required=True, widget=CustomClearableFileInputFr())
    class Meta:
        model = User
        fields = ['avatar']

class ChangeAvatarFormSp(forms.ModelForm):
    avatar = forms.ImageField(label='Your Avatar', required=True, widget=CustomClearableFileInputSp())
    class Meta:
        model = User
        fields = ['avatar']

transcendence/website/templates/brique.html
{% extends "master.html" %}
{% load widget_tweaks %}
{% load static %}
{% load friends %}

{% block title %}
  Profile
{% endblock %}

{% block content %}
<html>
<head>
	<meta charset="utf-8">
	<title>ft_transcendence</title>
	<style>
		body { margin: 0; }
	</style>
</head>
<body>
	{% load static %}
	<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/110/three.min.js"></script>
	<script type="text/javascript">
		var userId = "{{ user_id}}";
	</script>
	<script type="module">

		import { initScene, animateGame } from "{% static '/js/game/brique/Scene.js' %}";
		import * as Game from "{% static '/js/game/brique/Game.js' %}";
		const { renderer, scene, camera, environmentBoundingBoxes } = initScene();
		Game.init(scene, environmentBoundingBoxes);
		animateGame(renderer, scene, camera);

</script>
</body>
</html>
{% endblock %}

transcendence/website/templates/custom_clearable_file_inputSp.html
{% if widget.is_initial %}
    <div>Avatar actual: <a href="{{ widget.value.url }}">{{ widget.value }}</a></div>
{% endif %}
<input type="file" name="avatar" id="id_avatar" accept="image/*">

transcendence/website/templates/login.html
{% extends "master.html" %}
{% load widget_tweaks %}

{% block title %}
	Login
{% endblock %}

{% block content %}
<body style="background-color: black;">
<div class="container" style="margin-top: 50px;">
	<form method="post" action="{% url 'login' %}"> <!-- Assurez-vous que l'URL correspond à votre vue de connexion -->
		{% csrf_token %}
		<div class="row text-center">
			<h1 class="display-5 text-center mb-0" style="color: #ffffff;">Login</h1>
			<p class="lead text-center mb-4" style="color: #ffffff;">Please enter your credentials to log in.</p>
		</div>

		{% for field in form  %}
			<div class="form-group mb-4">
				<label class="form-label" for="{{ field.id_for_label }}" style="color: #ffffff;">{{ field.label }}</label>
				{{ field|add_class:"form-control" }}
				{% if field.help_text %}
					<small class="form-text text-muted">{{ field.help_text }}</small>
				{% endif %}
				{% for error in field.errors %}
					<div class="alert alert-danger" role="alert">
						{{ error }}
					</div>
				{% endfor %}
			</div>
		{% endfor %}
		<div class="container-fluid text-center">
			<div class="row">
				<div class="col">
					<button type="submit" class="btn btn-primary btn-block col-3 mb-4">Log in</button>
					<p class="mt-3" style="color: #ffffff;">Don't have an account? <a href="{% url 'register' %}">Register here</a></p> <!-- Lien vers la page d'inscription -->
				</div>
			</div>
		</div>
  </form>
</div>
</body>
{% endblock %}

transcendence/website/templates/master.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
		{% if not exclude_css %}
			<link rel="stylesheet" href="{% static 'css/custom.css' %}?v=23">
		{% endif %}
		<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
		<title>{% block title %}{% endblock %}</title>
	</head>
	<body>
		{% if password_changed or avatar_changed or name_changed or friends_changed or game_changed %}
			<script src="{% static 'js/reload_changed.js' %}?v=02"></script>
		{% endif %}
	
		{% if messages %}
			<div id="alert-container">
				{% for message in messages %}
					<div class="alert alert-{{ message.tags }} alert-dismissible fade show alert-custom" role="alert">
						{{ message }}
						<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
					</div>
				{% endfor %}
			</div>
		{% endif %}
		<nav class="navbar" id="main-navbar" style="background-color: lightgrey; border-bottom-left-radius: 15px; border-bottom-right-radius: 15px;">
			<div class="container-fluid">
				<div class="d-flex justify-content-between align-items-center w-100">
					<a class="navbar-brand" id="name" href="/#">FT_TRANSCENDENCE</a>
					<div class="mx-auto">
						{% if user.is_authenticated %}
							{% if request.user.language == 'fr' %}
								Connecte en tant que {{ user.username }}
							{% elif request.user.language == 'sp' %}
								Conectado como {{ user.username }}
							{% else %}
								Connected as {{ user.username }}
							{% endif %}
						{% endif %}
					</div>
					<div class="d-flex align-items-center">
						{% if user.is_authenticated %}
						{% if request.path == '/pong/vs_ai/' or request.path == '/pong/two_players/' %}
						{% else %}
							<div class="btn-group me-2">
								<form id="language-form" method="post" action="{% url 'change_language' %}" style="display: none;">
									{% csrf_token %}
									<input type="hidden" name="language_code" id="language-input">
								</form>
									{% if user.is_authenticated and request.user.language == 'fr' %}
									<button type="button" class="btn btn-primary dropdown-toggle btn-custom-rounded" data-bs-toggle="dropdown" aria-expanded="false">Langue</button>
									{% elif user.is_authenticated and request.user.language == 'sp' %}
									<button type="button" class="btn btn-primary dropdown-toggle btn-custom-rounded" data-bs-toggle="dropdown" aria-expanded="false">Idioma</button>
									
									{% else %}
									<button type="button" class="btn btn-primary dropdown-toggle btn-custom-rounded" data-bs-toggle="dropdown" aria-expanded="false">Language</button>
									
									{% endif %}
								
								<ul class="dropdown-menu">
									<li><a class="dropdown-item" href="#" onclick="changeLanguage('fr')"><img src="{% static 'fr.png' %}" style="margin-right: 3px;"> Français</a></li>
									<li><a class="dropdown-item" href="#" onclick="changeLanguage('en')"><img src="{% static 'uk.png' %}" style="margin-right: 3px;"> English</a></li>
									<li><a class="dropdown-item" href="#" onclick="changeLanguage('sp')"><img src="{% static 'sp.png' %}" style="margin-right: 3px;"> Español</a></li>
								</ul>
							</div>
						{% endif %}
							{% if request.user.language == 'fr' %}
								<div class="btn-group" role="group" aria-label="no user">
									<a href="{% url 'logout' %}" class="btn btn-primary">Déconnexion</a>
									<a href="{% url 'profile' %}" class="btn btn-primary">Profil</a>
									<a href="{% url 'players' %}" class="btn btn-primary">Joueurs</a>
								</div>
							{% elif request.user.language == 'sp' %}
								<div class="btn-group" role="group" aria-label="no user">
									<a href="{% url 'logout' %}" class="btn btn-primary">Desconexión</a>
									<a href="{% url 'profile' %}" class="btn btn-primary">Perfil</a>
									<a href="{% url 'players' %}" class="btn btn-primary">Jugadores</a>
								</div>
							{% else %}
								<div class="btn-group" role="group" aria-label="no user">
									<a href="{% url 'logout' %}" class="btn btn-primary">Logout</a>
									<a href="{% url 'profile' %}" class="btn btn-primary">Profile</a>
									<a href="{% url 'players' %}" class="btn btn-primary">Players</a>
								</div>
							{% endif %}
						{% else %}
							<div class="btn-group" role="group" aria-label="no user">
								<a href="{% url 'login' %}" class="btn btn-primary">Login</a>
								<a href="{% url 'register' %}" class="btn btn-primary">Register</a>
							</div>
						{% endif %}
					</div>
				</div>
			</div>
		</nav>
	{% block content %}
	{% endblock %}
	<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
	<script src="{% static 'js/custom.js' %}?v=112"></script>
	</body>
</html>

transcendence/website/templates/match_display.html
<div class="match winner-top">
    <div class="match-top team">
        {% if match.participant1 %}
            <span class="seed">{{ match.participant1.seed }}</span>
            <span class="name">
                {{ match.participant1.user.username }}
            </span>
            {% if match.score_participant1 == None and request.user == match.participant1.user %}
				<a href="{% url 'play_match' match.id %}" class="play-match-link" data-match-id="{{ match.id }}" data-opponent-id="{{ match.participant1.user.id }}">
                    {% if user.is_authenticated and request.user.language == 'fr' %}
                    	<p style="margin-left: 40px; transform: translateY(7px);"><u>Jouer la partie</u></p>
                    {% elif user.is_authenticated and request.user.language == 'sp' %}
                    	<p style="margin-left: 40px; transform: translateY(7px);"><u>Jugar la partida</u></p>
                    {% else %}
                    	<p style="margin-left: 40px; transform: translateY(7px);"><u>Play the game</u></p>
                    {% endif %}
                </a>
            {% else %}
                <span class="score">{{ match.score_participant1 }}</span>
            {% endif %}
        {% else %}
            {% if user.is_authenticated and request.user.language == 'fr' %}
            AD
            {% elif user.is_authenticated and request.user.language == 'sp' %}
            AD
            {% else %}
            TBD
            {% endif %}
        {% endif %}
    </div>
    <div class="match-bottom team">
        {% if match.participant2 %}
            <span class="seed">{{ match.participant2.seed }}</span>
            <span class="name">
                {{ match.participant2.user.username }}
            </span>
            {% if match.score_participant2 == None and request.user == match.participant2.user %}
                <a href="{% url 'play_match' match.id %}" class="play-match-link" data-match-id="{{ match.id }}" data-opponent-id="{{ match.participant1.user.id }}">
                    {% if user.is_authenticated and request.user.language == 'fr' %}
						<p style="margin-left: 40px; transform: translateY(7px);"><u>Jouer la partie</u></p>
					{% elif user.is_authenticated and request.user.language == 'sp' %}
						<p style="margin-left: 40px; transform: translateY(7px);"><u>Jugar la partida</u></p>
					{% else %}
						<p style="margin-left: 40px; transform: translateY(7px);"><u>Play the game</u></p>
					{% endif %}
                </a>
            {% else %}
                <span class="score">{{ match.score_participant2 }}</span>
            {% endif %}
        {% else %}
            {% if user.is_authenticated and request.user.language == 'fr' %}
            AD
            {% elif user.is_authenticated and request.user.language == 'sp' %}
            AD
            {% else %}
            TBD
            {% endif %}
        {% endif %}
    </div>
	<div class="match-lines">
		<div class="line one"></div>
		<div class="line two"></div>
	</div>
	<div class="match-lines alt">
		<div class="line one"></div>
	</div>
</div>

transcendence/website/templates/match_display_r2_nobody.html
<div class="match winner-top">
	<div class="match-top team">
		<span class="seed">0</span>
		{% if user.is_authenticated and request.user.language == 'fr' %}
		<span class="name">AD</span>
		{% elif user.is_authenticated and request.user.language == 'sp' %}
		<span class="name">AD</span>
		{% else %}
		<span class="name">TBD</span>
		{% endif %}
		<span class="score">0</span>
	</div>
	<div class="match-bottom team">
		<span class="seed">0</span>
		{% if user.is_authenticated and request.user.language == 'fr' %}
		<span class="name">AD</span>
		{% elif user.is_authenticated and request.user.language == 'sp' %}
		<span class="name">AD</span>
		{% else %}
		<span class="name">TBD</span>
		{% endif %}
		<span class="score">0</span>
	</div>
	<div class="match-lines">
		<div class="line one"></div>
		<div class="line two"></div>
	</div>
	<div class="match-lines alt">
		<div class="line one"></div>
	</div>
</div>